### ISSUE TITLE
Allow to report the database reference

### ISSUE THREAD

**Issue by fidalgo** [basecamp/marginalia#102]
From the guides https://guides.rubyonrails.org/active_record_multiple_databases.html on multiple databases, we have the following `database.yml` file:
```
production:
  primary:
    database: my_primary_database
    user: root
    adapter: mysql
  primary_replica:
    database: my_primary_database
    user: root_readonly
    adapter: mysql
    replica: true
  animals:
    database: my_animals_database
    user: animals_root
    adapter: mysql
    migrations_paths: db/animals_migrate
  animals_replica:
    database: my_animals_database
    user: animals_readonly
    adapter: mysql
    replica: true
```
I would like to signal which database the query is running. Given the replicas have the same database name, the `database` comment on marginalia won't work.
Is it possible to add the `animals` and `animals_replica` names to the comments?
